### ISSUE TITLE
Feature Milestones

### ISSUE THREAD

**Issue by pedro-rodrigues-primavera** [cebe/gnucash-php#1]
I'm in the need of a PHP reader for gnucash files, would you consider creating a list of pending features in the issue tracker in order to me to start contributing?

**Comment by cebe** [comment]
sorry for the late response. Its a long time since I made this so I would need to take a deeper look but I'll try to summarize the open issues soon.

**Comment by cebe** [comment]
I have checked out the code and it was basically a start on an implementation which is not finished. What is very needed for this library to be useful would be a set of unit tests that verify the behavoir. Using these tests it will be obvious which parts are missing or need work.
So it would be great if you could create some example files and write PHPUnit tests to verify they are represented correctly in form of PHP classes. Thanks in advance!

**Comment by pedro-rodrigues-primavera** [comment]
I've actually just noted a MySQL driver optional add-on to GnuCash (it 
doesn't come pre-bundled on Ubuntu) which makes the project kinda of 
useless for my use case.

I basically just need weekly transaction reports on a website, and I 
rather prefer to come up with some MySQL queries and then call those 
from PHP to display on HTML tables.

Not sure if this functionality of GnuCash was available at the time you 
wrote that, but I assume not. For the reasons above I will not embrace 
the project.

**Comment by cebe** [comment]
yeah, MySQL was available but I had already created a complete book over two years in the file format.
Thank you anyway.

**Comment by pedro-rodrigues-primavera** [comment]
May I know the books name ?

**Comment by cebe** [comment]
I was talking about a gnucash book :) https://github.com/cebe/gnucash-php/blob/master/entities/Book.php
